from azure.cognitiveservices.customvision.training import CustomVisionTrainingClient
from azure.cognitiveservices.customvision.training.prediction import CustomVisionPredictionClient
from azure.cognitiveservices.customvision.training.models import ImageFileCreateBatch, ImageFileCreateEntry, Region